version: '3'

services:

  # Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django

  # Django сервер
  django:
    build: .
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    expose:
      - "8000"
    depends_on:
      - redis

  # Сelery worker
  celery_worker:
    build: .
    volumes:
      - .:/app
    command: ["celery", "-A", "FactoryApp", "worker", "--loglevel=info"]
    depends_on:
      - redis

  # Celery beat
  celery_beat:
    build: .
    volumes:
      - .:/app
    command: ["celery", "-A", "FactoryApp", "beat", "--loglevel=info"]
    depends_on:
      - redis

  # Бот
  bot:
    build: .
    volumes:
      - .:/app
    command: ["python", "manage.py", "runbot"]
    depends_on:
      - redis

  # Redis сервер
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
