# Generated by Django 4.2.6 on 2023-10-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_token',
            field=models.CharField(blank=True, default='a602acba-20cc-4c05-b075-f29cd1cc3cb1', max_length=100, null=True),
        ),
    ]
