# Generated by Django 4.2.6 on 2023-10-13 15:04

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_telegram_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_token',
            field=models.CharField(blank=True, default=apps.users.models.generate_telegram_token, max_length=100, null=True),
        ),
    ]
